### ISSUE TITLE
Incorrect patching of PlayFab max player count for dedicated servers

### ISSUE THREAD

**Issue by ollaxe** [AzumattDev/MaxPlayerCount#1]
Hello! One of the people who worked on the crossplay implementation in Valheim here! 👋

About this line:
`(sbyte)instruction.operand == 11) // 10 is the default player limit when looking at the IL code, but for some reason my debug log above prints 11 for where the 10 should be. Changing this to 11 fixes the issue.`
https://github.com/AzumattDev/MaxPlayerCount/blob/a833bff0989a3cdcf2ccadb8da43e72a4b582408/Plugin.cs#L176C8-L176C8

The reason this value is 11 is that, the way the PlayFab implementation works, the dedicated server counts as a player in the PlayFab lobby. Therefore we need to have 11 player slots in the PlayFab lobby to account for 10 clients and 1 dedicated server being connected. When you patch this value, you should set it to the max player count + 1 to get the correct behavior. Otherwise the player limit will be 1 less than specified for dedicated servers using crossplay.

**Comment by AzumattDev** [comment]
I see, so when changing the value, just make it be one greater than normal? Seems simple enough.

**Comment by AzumattDev** [comment]
Fixed in https://github.com/AzumattDev/MaxPlayerCount/commit/8e663e0f5c9d235ea756af6331ad5e46a9dc64b5
